name: Publish to Docker Hub

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号：'
        required: true
        default: '1.12.0'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up docker-buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: v0.4.1
          qemu-version: 4.2.0-7
      - name: build & publish
        run: |
          sh git.sh -v ${{github.event.inputs.version}}
          VERSION=${GITHUB_REF:10}
          docker login \
            --username wanrenzhizun \
            --password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker buildx build \
            --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/s390x \
            --push \
            --tag wanrenzhizun/yapi:latest \
            --tag wanrenzhizun/yapi:${{github.event.inputs.version}} .
